"""add required_membership_type to agent

Revision ID: 44ed2273699a
Revises: d936ec56f8e8
Create Date: 2025-10-02 11:13:16.061674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '44ed2273699a'
down_revision: Union[str, None] = 'd936ec56f8e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加列为可空，并设置默认值为 'FREE'
    op.add_column('agent', sa.Column('required_membership_type', sa.Enum('FREE', 'MONTHLY', 'YEARLY', name='membershiptype'), nullable=True, server_default='FREE'))
    
    # 更新所有现有行的默认值
    op.execute("UPDATE agent SET required_membership_type = 'FREE' WHERE required_membership_type IS NULL")
    
    # 修改列为非空
    op.alter_column('agent', 'required_membership_type', nullable=False)
    
    # 创建索引
    op.create_index(op.f('ix_agent_required_membership_type'), 'agent', ['required_membership_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_required_membership_type'), table_name='agent')
    op.drop_column('agent', 'required_membership_type')
    # ### end Alembic commands ###
